### ISSUE TITLE
Assertion error when subsequently observing with same source port

### ISSUE THREAD

**Issue by bbc2** [chrysn/aiocoap#10]
A client can cause a server with an observable resource to crash with and assertion error.  See the following gist: https://gist.github.com/bbc2/9509c171bc2b6e0fa01d.

While `server.py` is running, first run `client.py`, then stop it and run it a second time.  The server will throw an exception when notifying the second observer with:
```
Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 119, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 932, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/home/bertrand/util/pyenv/coap/lib/python3.4/site-packages/aiocoap-0.1_git-py3.4.egg/aiocoap/protocol.py", line 159, in datagram_received
    self._dispatch_message(message)
  File "/home/bertrand/util/pyenv/coap/lib/python3.4/site-packages/aiocoap-0.1_git-py3.4.egg/aiocoap/protocol.py", line 194, in _dispatch_message
    self._remove_exchange(message)
  File "/home/bertrand/util/pyenv/coap/lib/python3.4/site-packages/aiocoap-0.1_git-py3.4.egg/aiocoap/protocol.py", line 310, in _remove_exchange
    self._send(next_message, exchange_monitor)
  File "/home/bertrand/util/pyenv/coap/lib/python3.4/site-packages/aiocoap-0.1_git-py3.4.egg/aiocoap/protocol.py", line 439, in _send
    self._add_exchange(message, exchange_monitor)
  File "/home/bertrand/util/pyenv/coap/lib/python3.4/site-packages/aiocoap-0.1_git-py3.4.egg/aiocoap/protocol.py", line 270, in _add_exchange
    assert message.remote not in self._backlogs
AssertionError
```

I know the client should probably not reuse the source port, but this would be useful in my case.  Even if this use case is invalid, I am not sure such an exception should occur.

**Comment by chrysn** [comment]
much of the observation code has been cleaned up since this was reported; with the current version, i did not see any exceptions raising from your code.

if this still causes trouble in a different form (eg. with another client), please open again. sorry this took so long.
