### ISSUE TITLE
aiocoap on rapberry pi error 97

### ISSUE THREAD

**Issue by vnahmias** [chrysn/aiocoap#112]
Hello i am trying to run the client.put.py on a raspberry pi, the server runs on a local network. So i think i only need to put the ip adress of my server into the file and then run it. However i have this error : 

```
Traceback (most recent call last):
  File "clientPUT.py", line 44, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "clientPUT.py", line 28, in main
    context = await Context.create_client_context()
  File "/home/pi/Downloads/aiocoap-master/aiocoap/protocol.py", line 172, in create_client_context
    from .transports.udp6 import MessageInterfaceUDP6
  File "/home/pi/Downloads/aiocoap-master/aiocoap/transports/udp6.py", line 73
    [Errno 97] Address family not supported by protocol    def __init__(self, sockaddr, *, pktinfo=None):
            ^
SyntaxError: invalid syntax
```

I tried to run client.GET.py, server.py and client.PUT.py on the same computer and it was working perfectly so if you have any solutions it would be great !

**Comment by aellwein** [comment]
> [Errno 97] Address family not supported by protocol  

From my understanding, aiocoap requires support of IPv6 to be enabled in OS. It seems like your system does not have this enabled.

**Comment by chrysn** [comment]
The backtrace is pretty garbled, looks like the udp6.py file was overwritten? Please try to clean that up (possibly by removing your aiocoap copy and [installing the development version as documented](http://aiocoap.readthedocs.io/en/latest/installation.html#development-version)) and paste a new backtrace from running `clientPUT.py` along with any modifications you have done to that program.

As the error message Errno-97 that occurred at some point in this, I think aellwein got it right: Is IPv6 enabled on your system? (On regular Linux systems it is, even if you don't have v6 from your internet provider, unless you deliberately disabled it). If not, you can either

* enable it again (which is really the recommended way)
* or, if that is absolutely no option eg. because you're running a kernel so old it does not support IPv6: use one of the transports for less-features operating systems by setting the AIOCOAP_CLIENT_TRANSPORT=simple6 environment variable; keep in mind that this reduces CoAP protocol compliance and that the way of setting those transports is an unstable feature.

**Comment by vnahmias** [comment]
I assume that ipv6 is enabled on my pi cause when i run ifconfig i have an ipv6 address. i did not modified any file except clientPUT and clientGET to create new resources and modify message sent. I will try to reinstall it and then i'll tell you.

**Comment by vnahmias** [comment]
Hi thanks for your answer. It seems that my IPV6 was disabled so i followed this tutorial : https://www.pihomeserver.fr/en/2015/02/18/configurer-lipv6-sur-le-raspberry-pi/

but it seems to be inefficient for example when i run ping6 ipv6.google.com i got `ping: socket: Address family not supported by protocol`  if someone could help me it would be great !

**Comment by vnahmias** [comment]
result of `uname -a` (to get system infos) : 
`Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux`

result of `grep -r . /sys/module/ipv6/parameters` : 
```
/sys/module/ipv6/parameters/disable:1
/sys/module/ipv6/parameters/disable_ipv6:0
/sys/module/ipv6/parameters/autoconf:1
```
result of `grep . /proc/sys/net/ipv6/conf/*/*ipv6*` : 
`grep: /proc/sys/net/ipv6/conf/*/*ipv6*: No such file or directory`

result of  `ip - 6 a` : 
nothing

**Comment by chrysn** [comment]
On Fri, Jun 15, 2018 at 08:34:15AM -0700, vnahmias wrote:
> /sys/module/ipv6/parameters/disable:1

That's the offender. There might be a "ipv6.disable=1" in
`/boot/cmdline.txt`, you can try removing that parameter and see whether
rebooting after that is sufficient.

(That's probably a good place to point out that you should not trust
what I'm saying too much given that I've never had my hands on a
raspberry because rumor has it they do all kinds of strange things...)

**Comment by aellwein** [comment]
Right, must be a kernel boot parameter, which disables ipv6 networking completely.

> (That's probably a good place to point out that you should not trust
> what I'm saying too much given that I've never had my hands on a
> raspberry because rumor has it they do all kinds of strange things...)

lol :-)

**Comment by chrysn** [comment]
Follow-up: Migth also be that there's someting in
/etc/modprobe.d/ipv6.conf or similar.

**Comment by vnahmias** [comment]
i can't fine the line "ipv6.disable=1" neither in boot/cmdline.txt or /etc/modprobe.d/ipv6.conf.

btw /etc/modprobe.d/ipv6.conf contains those lines : 
```
# Don't load ipv6 by default
alias net-pf-10 off
#alias ipv6 off
```

**Comment by chrysn** [comment]
On Fri, Jun 15, 2018 at 09:00:03AM -0700, vnahmias wrote:
> i can't fine the line "ipv6.disable=1" neither in boot/cmdline.txt or
> /etc/modprobe.d/ipv6.conf.

Surprising, that is. Lost a module parameter we have, how embarrassing.
</yoda>

What das `cat /proc/cmdline` say?

Is there anything in `grep -ri ipv6 /etc |grep disable`?

Have you rebooted after you've taken the last actions, if you've already
taken any?

**Comment by vnahmias** [comment]
`cat /proc/cmdline` gives : 
`bcm2708_fb.fbwidth=1920 bcm2708_fb.fbheight=1080 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=PARTUUID=8282befb-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles,disable_ipv6=0`
but i added the "disable_ipv6=0" my self
 
`grep -ri ipv6 /etc |grep disable` gives :  
`/etc/modprobe.d/usgcb-blacklist.conf:options ipv6 disable=1`

and yeah i reboot the pi after every modifs i do on conf files

**Comment by chrysn** [comment]
> `/etc/modprobe.d/usgcb-blacklist.conf:options ipv6 disable=1`

Bingo, try removing that line.

Then, please do `dpkg-query -S /etc/modprobe.d/usgcb-blacklist.conf` to
see which package(r) was ...  presumptiuous enough to just claim that
you won't ever need IPv6 (or even just the basic standardized socket API
(RFC3542) it brings, which is why aiocoap relies on it).

**Comment by vnahmias** [comment]
i've set the parameter to 0 and now i have an ipv6 adress and i am able to ping ipv6.google.com however when i ran `dpkg-query -S /etc/modprobe.d/usgcb-blacklist.conf` i have : 
`dpkg-query: no path found matching pattern /etc/modprobe.d/usgcb-blacklist.conf`

**Comment by chrysn** [comment]
On Fri, Jun 15, 2018 at 04:58:46PM +0000, vnahmias wrote:
> i've set the parameter to 0 and now i have an ipv6 adress and i am able to ping ipv6.google.com

Great -- and how is that clientPOST.py coming?

> however when i ran `dpkg-query -S /etc/modprobe.d/usgcb-blacklist.conf` i have : 
> `dpkg-query: no path found matching pattern /etc/modprobe.d/usgcb-blacklist.conf`

That's not really related to debugging any more, but out of curiosity,
could you paste that file to some place like <http://paste.debian.net/>?
