### ISSUE TITLE
tests fail with Python 3.7.1

### ISSUE THREAD

**Issue by mwhudson** [chrysn/aiocoap#127]
[This change](https://github.com/python/cpython/commit/3b699932e5ac3e76031bbb6d700fbea07492641d) in Python 3.7.1 causes almost every test to fail like this:

```
======================================================================
ERROR: test_unacceptable_accept (tests.test_server.TestServerTCP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/aiocoap/tests/test_server.py", line 107, in setUp
    super(WithTestServer, self).setUp()
  File "/root/aiocoap/tests/test_server.py", line 125, in setUp
    super(WithClient, self).setUp()
  File "/root/aiocoap/tests/fixtures.py", line 131, in setUp
    super(WithAsyncLoop, self).setUp()
  File "/root/aiocoap/tests/fixtures.py", line 95, in setUp
    self.handler = self.ListHandler()
  File "/usr/lib/python3.7/logging/__init__.py", line 824, in __init__
    self.createLock()
  File "/usr/lib/python3.7/logging/__init__.py", line 847, in createLock
    _register_at_fork_acquire_release(self)
  File "/usr/lib/python3.7/logging/__init__.py", line 250, in _register_at_fork_acquire_release
    _at_fork_acquire_release_weakset.add(instance)
  File "/usr/lib/python3.7/_weakrefset.py", line 84, in add
    self.data.add(ref(item, self._remove))
TypeError: unhashable type: 'ListHandler'
```

I guess it could be argued that this change in behaviour in CPython is a bit obnoxious, but it looks like it's only a test server so it's probably easiest to just change that (I'll try to come up with a patch shortly).

**Comment by chrysn** [comment]
Thank you. This needed some fixes (add super() in init, add iterator), but is now merged into master.

I've changed the CI to run with 3.7 as well, though I can't tell exactly which version gets tested in the docker runs.
