### ISSUE TITLE
"No request interface could route message"

### ISSUE THREAD

**Issue by brean** [chrysn/aiocoap#136]
Hi,

I am trying to using aiocoap from github/master with asyncio (aiohttp) to get data from my tradfri-devices using pytradfri (also from github/master), but it instead of some device data I am getting this RuntimeError:
```
Traceback (most recent call last):
  File "/home/brean/.local/share/virtualenvs/home_service-cPNi1D6n/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 406, in start
    resp = await task
  File "/home/brean/.local/share/virtualenvs/home_service-cPNi1D6n/lib/python3.7/site-packages/aiohttp/web_app.py", line 435, in _handle
    resp = await handler(request)
  File "/home/brean/coding/home/home_service/web/modules/tradfri/routes.py", line 9, in handle_list_devices
    data = await list_data(request)
  File "/home/brean/coding/home/home_service/web/modules/tradfri/tradfri.py", line 41, in list_data
    groups = await api(gateway.get_groups())
  File "/home/brean/.local/share/virtualenvs/home_service-cPNi1D6n/lib/python3.7/site-packages/pytradfri/api/aiocoap_api.py", line 155, in request
    result = await self._execute(api_commands)
  File "/home/brean/.local/share/virtualenvs/home_service-cPNi1D6n/lib/python3.7/site-packages/pytradfri/api/aiocoap_api.py", line 146, in _execute
    _, res = await self._get_response(msg)
  File "/home/brean/.local/share/virtualenvs/home_service-cPNi1D6n/lib/python3.7/site-packages/pytradfri/api/aiocoap_api.py", line 95, in _get_response
    r = await pr.response
  File "/home/brean/.local/share/virtualenvs/home_service-cPNi1D6n/lib/python3.7/site-packages/aiocoap/protocol.py", line 718, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/home/brean/.local/share/virtualenvs/home_service-cPNi1D6n/lib/python3.7/site-packages/aiocoap/protocol.py", line 743, in _run
    await protocol.find_remote_and_interface(app_request)
  File "/home/brean/.local/share/virtualenvs/home_service-cPNi1D6n/lib/python3.7/site-packages/aiocoap/protocol.py", line 295, in find_remote_and_interface
    raise RuntimeError("No request interface could route message")
RuntimeError: No request interface could route message
```

the message is: `<aiocoap.Message at 0x7f334eae8278: no mtype, GET (no MID, empty token) remote UndecidedRemote(scheme='coaps', hostinfo='192.168.1.66:5684'), 2 option(s)>`

self.request_interfaces is: `[<aiocoap.tokenmanager.TokenManager object at 0x7fb2a9e3ca58>, <aiocoap.tokenmanager.TokenManager object at 0x7fb2a9e1b7b8>, <aiocoap.tokenmanager.TokenManager object at 0x7fb2a9e1b9b0>]`

I don't know how to debug this any further, but hope someone can help. I am happy to provide more information.

I am using the [async-example](https://github.com/ggravlingen/pytradfri/blob/master/examples/example_async.py) for testing, it breaks at [line 81](https://github.com/ggravlingen/pytradfri/blob/master/examples/example_async.py#L81): `devices_commands = await api(devices_command)`.

**Comment by chrysn** [comment]
Did you install aiocoap with the extras for DTLS as per installation docs, or otherwise make the DTLSSocket module avallable?

**Comment by brean** [comment]
No, `pipenv install DTLSSocket` helped, but I got an authentification error and needed to monkey-patch pytradfri, (described [here](https://github.com/ggravlingen/pytradfri/issues/176#issuecomment-405744560) )

Thank you for your help!
