### ISSUE TITLE
AttributeError: 'RecvmsgSelectorDatagramTransport' object has no attribute '_fatal_error'

### ISSUE THREAD

**Issue by aseemjakhar** [chrysn/aiocoap#212]
Not able to find the definition for _fatal_error.

I'm trying to run request() using a new loop in my application. I was calling shutdown() before request(request).response on the Context object which I understand is wrong. However, I am not able to find `_fatal_error` in the code.

Stack Trace:
File "coap/__init__.py", line 79, in request
    response = await ctx.request(request).response
  File "python3.7/site-packages/aiocoap-0.4b3-py3.7.egg/aiocoap/protocol.py", line 731, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "python3.7/site-packages/aiocoap-0.4b3-py3.7.egg/aiocoap/protocol.py", line 783, in _run
    blockresponse = await blockrequest.response
  File "python3.7/site-packages/aiocoap-0.4b3-py3.7.egg/aiocoap/tokenmanager.py", line 210, in request
    send_canceller = self.token_interface.send_message(msg)
  File "python3.7/site-packages/aiocoap-0.4b3-py3.7.egg/aiocoap/messagemanager.py", line 406, in send_message
    self._send_initially(message, exchange_monitor)
  File "python3.7/site-packages/aiocoap-0.4b3-py3.7.egg/aiocoap/messagemanager.py", line 421, in _send_initially
    self._send_via_transport(message)
  File "python3.7/site-packages/aiocoap-0.4b3-py3.7.egg/aiocoap/messagemanager.py", line 426, in _send_via_transport
    self.message_interface.send(message)
  File "python3.7/site-packages/aiocoap-0.4b3-py3.7.egg/aiocoap/transports/udp6.py", line 291, in send
    self.transport.sendmsg(message.encode(), ancdata, 0, message.remote.sockaddr)
  File "python3.7/site-packages/aiocoap-0.4b3-py3.7.egg/aiocoap/util/asyncio/recvmsg.py", line 110, in sendmsg
    self._fatal_error(exc,
AttributeError: 'RecvmsgSelectorDatagramTransport' object has no attribute '_fatal_error'

**Comment by upuetz** [comment]
I get the same exeption 
>>>  _AttributeError: 'RecvmsgSelectorDatagramTransport' object has no attribute '_fatal_error'_
 when trying to overtake an ONVIS thread switch (HS2) from Homekit:


2023-10-23 14:50:04.596 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/pairing.py", line 111, in _ensure_connected
    await self.connection_future
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/connection.py", line 399, in connect
    await self.get_accessory_info()
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/connection.py", line 435, in get_accessory_info
    results = await self.enc_ctx.post_all(OpCode.CHAR_READ, iids, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/connection.py", line 196, in post_all
    res_pdu = await self.post_bytes(req_pdu)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/connection.py", line 170, in post_bytes
    response = await self.coap_ctx.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiocoap/protocol.py", line 606, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.11/site-packages/aiocoap/protocol.py", line 665, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aiocoap.error.LibraryShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 454, in async_step_pair
    return await self._entry_from_accessory(pairing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 582, in _entry_from_accessory
    name = await pairing.get_primary_name()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/abstract.py", line 264, in get_primary_name
    accessories = await self.list_accessories_and_characteristics()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/pairing.py", line 147, in list_accessories_and_characteristics
    await self._ensure_connected()
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/pairing.py", line 113, in _ensure_connected
    raise AccessoryDisconnectedError("failed to connect")
aiohomekit.exceptions.AccessoryDisconnectedError: failed to connect
2023-10-23 14:50:04.620 WARNING (MainThread) [coap-server] An exception that is not an aiocoap Error was raised from a transport; please report this as a bug in aiocoap: AttributeError("'RecvmsgSelectorDatagramTransport' object has no attribute '_fatal_error'")
2023-10-23 14:50:04.624 ERROR (MainThread) [aiohomekit.utils] Failure running background task: Task-13730
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiocoap/util/asyncio/recvmsg.py", line 126, in sendmsg
    self.__sock.sendmsg((data,), ancdata, flags, address)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sendmsg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/utils.py", line 40, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/pairing.py", line 169, in _process_config_changed
    await self.list_accessories_and_characteristics()
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/pairing.py", line 149, in list_accessories_and_characteristics
    accessories = await self.connection.get_accessory_info()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/connection.py", line 408, in get_accessory_info
    _, body = await self.enc_ctx.post(OpCode.UNK_09_READ_GATT, 0x0000, b"")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/connection.py", line 189, in post
    res_pdu = await self.post_bytes(req_pdu)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/coap/connection.py", line 170, in post_bytes
    response = await self.coap_ctx.request(request).response
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiocoap/protocol.py", line 606, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.11/site-packages/aiocoap/protocol.py", line 665, in _run
    blockresponse = await blockrequest.response
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiocoap/tokenmanager.py", line 219, in request
    send_canceller = self.token_interface.send_message(msg, lambda: request.add_exception(error.MessageError))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiocoap/messagemanager.py", line 419, in send_message
    self._send_initially(message, messageerror_monitor)
  File "/usr/local/lib/python3.11/site-packages/aiocoap/messagemanager.py", line 432, in _send_initially
    self._send_via_transport(message)
  File "/usr/local/lib/python3.11/site-packages/aiocoap/messagemanager.py", line 437, in _send_via_transport
    self.message_interface.send(message)
  File "/usr/local/lib/python3.11/site-packages/aiocoap/transports/udp6.py", line 356, in send
    self.transport.sendmsg(message.encode(), ancdata, 0, message.remote.sockaddr)
  File "/usr/local/lib/python3.11/site-packages/aiocoap/util/asyncio/recvmsg.py", line 132, in sendmsg
    self._fatal_error(exc,
    ^^^^^^^^^^^^^^^^^
AttributeError: 'RecvmsgSelectorDatagramTransport' object has no attribute '_fatal_error'
